* Data Science Job Search
** List of Geographical areas
Silicon Valley
Seattle
** Target Industries
Large Companies specializing in AI.
Small companies solving specific AI problems.
No specific industry targeted.
** List of companies to target
Google
Amazon
IBM
Apple
Workday
Nvidia
Cisco
Quora
Euclid Analytics
Planatir
Microsoft
Zillow
** List of Data Scientists near me or known to me
*** Michael Beaumier
https://www.linkedin.com/in/michaelbeaumier/
"leading international collaborations between business stakeholders and technical experts"
Ask if collaboration is more important than technical expertise.
What should I target for my work?
*** Jeff Moulton
https://www.linkedin.com/in/jeff-moulton-a2729b20/
"interested in statistical computing, machine learning, and optimization"
Ask if he thinks statistical computing or machine learning is going to be the way to go.
What should I target for my work?
*** Praveen Dua 
https://www.linkedin.com/in/praveendua/
At Lore IO.  This is what their website says:
"It generates standard outputs without the need for engineers to develop 
procedural ETL and data pipelines." 
He converted from Chip Engineering role to Data Scientist at Lore IO.
Ask him about his new role.

Hi Praveen,

It's been a while since we were at Atheros.  It looks like you have found
a new interest in Data Science.  I have joined Lambda School and started
my Data Science journey as well.

I know this is out of the blue, but if you have some time to talk,
I would very much like to get your read on where Data Science is going,
and what I can do to prepare for it.

Hope to see you soon,
Samir

*** Soner Ozgur
https://www.linkedin.com/in/soner-ozgur-4b73501/
At Plume Design.  Talk to him about Atheros/Broadcom.
Explain you are doing exactly the same thing as he is -
moving from chip industry to data science.
*** Jeff Liew 
https://www.linkedin.com/in/jeff-liew-78596a4/
At Plume Design.  Talk to him about Atheros/Proxim.
*** Michael Zhu
https://www.linkedin.com/in/mikezhu/
He is Head of Software Engineering at Amazon Web Services.
He was at Broadcom while I was there.
Talk to him about what help he needs now.
His LinkedIn site says "I am hiring Leaders and Engineers in Cloud, 
Fullstack, Mobile, Computer Vision, Deep Learning & NLP"

